
############################### BASIC CAN RUN APP ON CMD NO UI ###################################

# #Use a suitable base image
# FROM mcr.microsoft.com/windows:ltsc2019

# # Create a directory for your application
# WORKDIR C:/app

# # Copy your application files into the container
# COPY . .

# # Set the entry point for your application
# ENTRYPOINT ["bin/EventMaster.exe"]

############################### USING TIGHTVNC ###################################


# # Use a Windows base image
# FROM mcr.microsoft.com/windows:ltsc2019

# # Download TightVNC installer
# ADD https://sourceforge.net/projects/turbovnc/files/3.0.1/TurboVNC-3.0.1-x64.exe/download C:/turbovnc.exe

# # Install TightVNC silently
# RUN C:/turbovnc.exe /S

# # Clean up installer
# RUN del C:/turbovnc.exe

# # Copy the installed application directory from the host machine into the container
# COPY . C:/app

# # Expose RDP port
# EXPOSE 3389

# # Set the working directory to the installed application directory
# WORKDIR C:/app

# # Start the RDP server and GUI application
# CMD ["cmd.exe", "/c", "C:/Program Files/TurboVNC/vncviewer.exe & start bin/EventMaster.exe"]

########################### USING WINDOWS IMAGE WITH RDP PORT ####################################################

# # Use a Windows base image
# FROM mcr.microsoft.com/windows:ltsc2019

# # Expose RDP port
# EXPOSE 3389

# # Copy the installed application directory from the host machine into the container
# COPY . C:/app


# # Set the working directory to the installed application directory
# WORKDIR C:/app

# # Start the RDP server and GUI application
# ENTRYPOINT ["bin/EventMaster.exe"]


###################### USING TURBO VNC ###################################################################

# Use a Windows base image
# FROM mcr.microsoft.com/windows:ltsc2019

# # Install TurboVNC
# ADD https://sourceforge.net/projects/turbovnc/files/2.2.6/TurboVNC-2.2.6-x64.exe/download C:/turbovnc.exe

# RUN C:/turbovnc.exe

# # Clean up the installer file
# RUN del C:/turbovnc.exe

# # Copy the installed application directory from the host machine into the container
# COPY . C:Application

# # Expose RDP port
# EXPOSE 3389

# # Set the working directory to the installed application directory
# WORKDIR C:/Application

# # Start the TurboVNC server and GUI application
# CMD ["cmd.exe", "/c", "C:/Program Files/TurboVNC/tvnserver.exe & start bin/EventMaster.exe"]

############################### USING RDP AND SOME MORE INTERESTING COMMAND (CHATGPT) ###################################

# Use the base Windows image
FROM mcr.microsoft.com/windows:ltsc2019

# Set environment variables to suppress Windows Update prompts
ENV ACCEPT_EULA=Y
ENV EULA=Y

# Expose RDP Port
EXPOSE 3389

# Copy the installed application directory from the host machine into the container
COPY . C:/app

# Set the working directory to the installed application directory
WORKDIR C:/app

# Install necessary dependencies for GUI application (if any)

# Install PowerShell Core

# Start the RDP server and GUI application

ENTRYPOINT ["bin/EventMaster.exe"]